spring:
    data:
        rest:
            basePath: /api
            defaultPageSize: 100
            returnBodyOnCreate: true
            returnBodyOnUpdate: true
    jpa:
        hibernate:
            ddl-auto: create-drop
    datasource:
        url: jdbc:mysql://demodb/demo?characterEncoding=UTF-8&useSSL=false
        username: user
        password: test